projectName: Top Identity and Access Management Challenges for Business
jsonFilePath: ./input.json
baseUrl: https://auth0.com
portalHeading: Top Identity and Access Management Challenges
portalDescription: >-
  Explore the top challenges in identity and access management and how Auth0 can
  help you overcome them.
portalTitle: Identity and Access Management Challenges
searchPlaceholder: Search for solutions...
useAlphabetsCategory: true
homeLink: https://auth0.com/
logoLink: https://auth0.com/
ctaText: Start Building for Free
aboutLink: https://auth0.com/about
productsLink: https://auth0.com/products
logoImgUrl: https://auth0.com/logo.png
ctaLink: https://auth0.com/signup
copyrightText: © 2023 Auth0, Inc. All rights reserved.
faviconUrl: https://auth0.com/favicon.ico
googleTagManagerId: GTM-XXXX
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: Twitter
    url: https://twitter.com/auth0
  - platform: LinkedIn
    url: https://www.linkedin.com/company/auth0
  - platform: Facebook
    url: https://www.facebook.com/auth0
theme:
  primaryColor: '#3A3A3A'
  secondaryColor: '#F5F5F5'
  backgroundColor: '#FFFFFF'
  textColor: '#000000'
  accentColor: '#FF5733'
fonts:
  - family: Arial
    weights:
      - 400
      - 500
      - 600
  - family: Roboto
    weights:
      - 500
      - 600
      - 700
